name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH agent and key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Deploy to server via SSH key
      - name: Deploy to server
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no hassanbilalchannel@api-events-service.codeinprogress.net << 'EOF'
            set -e
            cd /sites/events-microservice-app
            sudo git fetch origin main
            sudo git pull --ff-only origin main
            cd /sites/events-microservice-app/api-gateway
            sudo npm install
            sudo npm run build
            cd /sites/events-microservice-app/event-service
            sudo npm install
            sudo npm run build
            cd /sites/events-microservice-app/api-gateway
            pm2 restart all
          EOF
